name: cd

on:
  push:
    branches:
      - "main"

jobs:
  cd:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: infrastructure/
      TF_VAR_REGION: ${{secrets.TF_VAR_REGION}}
      TF_VAR_ACCESS_KEY: ${{secrets.TF_VAR_ACCESS_KEY}}
      TF_VAR_SECRET_KEY: ${{secrets.TF_VAR_SECRET_KEY}}
      TF_VAR_TOKEN: ${{secrets.TF_VAR_TOKEN}}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TF_VAR_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TF_VAR_SECRET_KEY }}
          aws-region: ${{secrets.TF_VAR_REGION}}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -input=false
        working-directory: ${{ env.WORKING_DIR }}
