name: cd

on:
  push:
    branches:
      - "main"

jobs:
  cd:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: infrastructure/
      TF_VAR_REGION: ${{secrets.TF_VAR_REGION}}
      TF_VAR_ACCESS_KEY: ${{secrets.TF_VAR_ACCESS_KEY}}
      TF_VAR_SECRET_KEY: ${{secrets.TF_VAR_SECRET_KEY}}
      TF_VAR_TOKEN: ${{secrets.TF_VAR_TOKEN}}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TF_VAR_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TF_VAR_SECRET_KEY }}
          aws-session-token: ${{ secrets.TF_VAR_TOKEN }}
          aws-region: ${{secrets.TF_VAR_REGION}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: demo-terraform
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo $PWD
          ls
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f ../code
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Plan
        id: plan
        env:
          TF_VAR_DOCKER_IMAGE: ${{ format('{0}/demo-terraform:{1}', steps.login-ecr.outputs.registry, github.sha) }}
        run: terraform plan -no-color
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Apply
        id: apply
        env:
          TF_VAR_DOCKER_IMAGE: ${{ format('{0}/demo-terraform:{1}', steps.login-ecr.outputs.registry, github.sha) }}
        run: terraform apply -auto-approve -input=false
        working-directory: ${{ env.WORKING_DIR }}
