name: cd

on:
  push:
    branches:
      - "main"

jobs:
  cd:
    runs-on: ubuntu-latest
    env:
        TF_WORKSPACE: stage
        WORKING_DIR: infrastructure/
        REGION: ${{secrets.TF_VAR_REGION}}
        ACCESS_KEY: ${{secrets.TF_VAR_ACCESS_KEY}}
        SECRET_KEY: ${{secrets.TF_VAR_SECRET_KEY}}
        TOKEN: ${{secrets.TF_VAR_TOKEN}}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Terraform 
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7

    - name: Terraform init
      run: terraform init
      working-directory: ${{ env.WORKING_DIR }}

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      working-directory: ${{ env.WORKING_DIR }}

    - run: echo ${{ steps.plan.outputs.stdout }}
    - run: echo ${{ steps.plan.outputs.stderr }}
    - run: echo ${{ steps.plan.outputs.exitcode }}
